Add missing QActionGroup include
I get a build error in some situations without this:

"kstars/kstars.cpp:205:48: error: invalid use of incomplete type
 'class QActionGroup'
  205 |         cschemeGroup    = new QActionGroup(this);"