Remove "libindi" prefix in header files
Summary:
Compiling KStars with INDI support requires correct INDI_INCLUDE_DIR such that ${INDI_INCLUDE_DIR}/indiapi.h can be find
in FindINDI.cmake.

Compiling and installing INDI (master) in e.g.

```
>ll /opt/indi
drwxr-xr-x 2 root root 4096 Jan  3 14:13 bin
drwxr-xr-x 3 root root 4096 Jan  3 14:13 include
drwxr-xr-x 4 root root 4096 Jan  3 14:13 lib
drwxr-xr-x 3 root root 4096 Jan  3 14:13 share
```

and compiling KStars as follows

```
cmake -DINDI_INCLUDE_DIR:PATH=/opt/indi/include/libindi .. && make
....
-- The following OPTIONAL packages have been found:

 * KF5NotifyConfig
 * CFitsio , FITS IO Library , <http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html>
   Support for the FITS (Flexible Image Transport System) data format in KStars.
 * INDI (required version >= 1.7.1) , Astronomical instrumentation control , <http://www.indilib.org>
   Support for controlling astronomical devices on Linux with KStars.
 * LibRaw , Library for reading RAW files , <http://www.libraw.org>
   Support for reading and displaying RAW files in KStars.
 * WCSLIB , World Coordinate System library , <http://www.atnf.csiro.au/people/mcalabre/WCS>
   WCS enables KStars to read and process world coordinate systems in FITS header.
 * Qt5Keychain
 * OpenGL , Open Graphics Library , <http://www.opengl.org>
   Support for hardware rendering in KStars.
 * PkgConfig
....
```

leads to error:

```

/tmp/kstars/kstars/ekos/manager.h:15:32: fatal error: libindi/baseclient.h: No such file or directory
 #include <libindi/baseclient.h>
```

In all but 2 remaining KStar header files the prefix "libindi" leads to this error and thus needs to be removed.

Reviewers: mutlaqja, yurchor

Reviewed By: mutlaqja, yurchor

Subscribers: yurchor, kde-edu

Tags: #kde_edu

Differential Revision: https://phabricator.kde.org/D17940